# Generated by Django 5.2.7 on 2026-02-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrusion_app', '0002_blockedip_modelmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('Port Scan', 'Port Scan'), ('Brute Force', 'Brute Force Attack'), ('DDoS', 'DDoS Attack'), ('Malware', 'Malware Detection'), ('Anomaly', 'AI Anomaly'), ('Suspicious Port', 'Suspicious Port Access'), ('SQL Injection', 'SQL Injection'), ('XSS', 'Cross-Site Scripting'), ('Unknown', 'Unknown Attack')], max_length=50)),
                ('source_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('destination_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
