# Generated by Django 5.2.7 on 2025-10-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('attack_type', models.CharField(choices=[('DoS', 'DoS'), ('Probe', 'Probe'), ('R2L', 'R2L'), ('U2R', 'U2R'), ('Normal', 'Normal')], max_length=20)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10)),
            ],
        ),
    ]
